image: python:3.14

stages:
  - test

cache:
  paths:
    - .cache/pip

pytest:
  stage: test
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  before_script:
    - python -V
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest
